### ISSUE TITLE
Running gives mounting trouble

### ISSUE THREAD

**Issue by abondrn** [wirehead/semantic-mediawiki-docker#1]
First of all, I just wanted to say great work on setting up the docker container, it's well documented and seems to be set up properly. However, running `run.sh` seems to give me issues.

I'm curious about this flag: `-v /home/wirehead/src/moinmoin2mediawiki/data-out/foo:/import`. I'm guessing this is meant to populate the wiki with content from one created with moinmoin?

Initially, I was getting this error:
```
docker: Error response from daemon: error while creating mount source path '/home/wirehead/src/moinmoin2mediawiki/data-out/foo': mkdir /home/wirehead: operation not supported.
ERRO[0000] error waiting for container: context canceled 
```
This was after adding `home` as a directory Docker could mount.

However, rerunning after removing this flag gave: `docker: invalid reference format.` Odd, seemed well formed to me.

My environment:
macOS Mojave Version 10.14
Docker Desktop 18.09.3

Advice on how to proceed? Apologies, I'm not that familiar with docker. Thanks.

**Comment by wirehead** [comment]
Yah, that flag shouldn't be there.  I pushed a change that works on my side that doesn't mount the unnecessary volume, can you see if it starts working?  `invalid reference format` usually means that there's something in the command line that looks like a docker container reference to docker but isn't.

My long-term intention is that the container ought to be run using Kubernetes using a helm chart, see https://github.com/wirehead/wirehead-charts/tree/master/charts/semanticmediawiki

I haven't tested it on Docker Desktop, just a real kube cluster, that should work.  

But it should work this way as well after the patch, so let me know if it starts to work...

**Comment by abondrn** [comment]
Just to update, the change you pushed works. However, now I'm coming across a database issue.

Hitting `http://localhost:8080/` gives `(Cannot access the database: Cannot return last error, no db connection)`

Checking the dependencies by running `php maintenance/update.php` in the shell reports `composer.lock` is up to date, but fails to establish a connection with the database:
```
[46c22f1d7270bbb9345b4500] [no req]   Wikimedia\Rdbms\DBConnectionError from line 1004 of /var/www/html/includes/libs/rdbms/database/Database.php: Cannot access the database: Cannot return last error, no db connection
Backtrace:
#0 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1134): Wikimedia\Rdbms\Database->reportConnectionError(string)
#1 /var/www/html/includes/libs/rdbms/loadbalancer/LoadBalancer.php(749): Wikimedia\Rdbms\LoadBalancer->reportConnectionError()
#2 /var/www/html/includes/GlobalFunctions.php(2801): Wikimedia\Rdbms\LoadBalancer->getConnection(integer, array, boolean)
#3 /var/www/html/maintenance/Maintenance.php(1311): wfGetDB(integer, array, boolean)
#4 /var/www/html/maintenance/update.php(147): Maintenance->getDB(integer)
#5 /var/www/html/maintenance/doMaintenance.php(94): UpdateMediaWiki->execute()
#6 /var/www/html/maintenance/update.php(248): require_once(string)
#7 {main}
```

`http://localhost:8080/mw-config/` appears functional at first, but reading the settings file gives the following error:
> Cannot access the database: SQLite database not accessible.
>
> Check the data directory and database name below and try again.

My guess? It's unclear how the database environment variables are being set. `LocalSettings.php` reads from the environment, however `local_changes` doesn't set any of these yet.

**Comment by wirehead** [comment]
Oh, that's probably a permissioning issue with the directory for sqlite.  Make sure that the directory is writable for the container's `www-data` user.

**Comment by abondrn** [comment]
Wasn't able to get this working, even after granting permissions for `www-data`. Additionally, there are two more issues:

The InterWiki extension is no longer importable, removing it from `LocalSettings.php` suppresses this.
> PHP Fatal error:  Uncaught Exception: /var/www/html/extensions/InterWiki/extension.json does not exist! in /var/www/html/includes/registration/ExtensionRegistry.php:117\nStack trace:\n#0 /var/www/html/includes/GlobalFunctions.php(50): ExtensionRegistry->queue('/var/www/html/e...')\n#1 /var/www/conf/LocalSettings.php(155): wfLoadExtension('InterWiki')\n#2 /var/www/html/includes/Setup.php(105): require_once('/var/www/conf/L...')\n#3 /var/www/html/includes/WebStart.php(77): require_once('/var/www/html/i...')\n#4 /var/www/html/index.php(39): require('/var/www/html/i...')\n#5 {main}\n  thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 117

Now, viewing the main page or configuring throws this error:
> PHP Fatal error:  Uncaught InvalidArgumentException: Schema must be null or a non-empty string. in /var/www/html/includes/libs/rdbms/database/domain/DatabaseDomain.php:50\nStack trace:\n#0 /var/www/html/includes/WikiMap.php(295): Wikimedia\\Rdbms\\DatabaseDomain->__construct('my_wiki', false, '')\n#1 /var/www/html/includes/objectcache/ObjectCache.php(157): WikiMap::getCurrentWikiDbDomain()\n#2 /var/www/html/includes/objectcache/ObjectCache.php(174): ObjectCache::getDefaultKeyspace()\n#3 /var/www/html/includes/objectcache/ObjectCache.php(137): ObjectCache::newFromParams(Array)\n#4 /var/www/html/includes/objectcache/ObjectCache.php(94): ObjectCache::newFromId(-1)\n#5 /var/www/html/extensions/SemanticMediaWiki/src/CacheFactory.php(134): ObjectCache::getInstance(-1)\n#6 /var/www/html/extensions/SemanticMediaWiki/src/CacheFactory.php(118): SMW\\CacheFactory->newMediaWikiCache(NULL)\n#7 /var/www/html/extensions/SemanticMediaWiki/src/Services/SharedServicesContainer.php(180): SMW\\CacheFactory->newMediaWikiCompositeCache(NULL)\n#8 [internal functi in /var/www/html/includes/libs/rdbms/database/domain/DatabaseDomain.php on line 50

**Comment by wirehead** [comment]
Oops.  I really need to set up actual unit tests for the container.  Try it now.

**Comment by abondrn** [comment]
Still didn't work. You're not using a different `local_settings`? Not running any additional commands? It went back to errors like `(Cannot access the database)`

I don't think this is a permission issue. I made sure the Apache directory was writable:
```
chown -R www-data:www-data /var/www                        
chmod -R 770 /var/www 
```
`sqlite` or `sqlite3` also aren't recognized. Is it an installation issue? Btw I'd be happy to look into unit tests.

**Comment by wirehead** [comment]
Hm, OK, so try using the `chown.sh` script that I just added, which should forcibly fix the permissions.
